### ISSUE TITLE
Error importing libsgfdata

### ISSUE THREAD

**Issue by danpejobo** [emerald-geomodelling/libsgfdata#32]
libsgfdata got installed as a dependency when i installed libnadagclient using pip. When i try to import it i get this error.

When i try to import libnadagclient
```
>>> import libnadagclient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libnadagclient\__init__.py", line 5, in <module>
    import libsgfdata
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libsgfdata\__init__.py", line 1, in <module>
    from .metadata import main, method, data, methods, comments
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libsgfdata\metadata.py", line 80, in <module>
    typemapped = typemap.loc[block.type].set_index(block.index)
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1089, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\pandas\core\common.py", line 134, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
```

When i try to import only libsgfdata
```
import libsgfdata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libsgfdata\__init__.py", line 1, in <module>
    from .metadata import main, method, data, methods, comments
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libsgfdata\metadata.py", line 80, in <module>
    typemapped = typemap.loc[block.type].set_index(block.index)
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1089, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\pandas\core\common.py", line 134, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
```

**Comment by redhog** [comment]
What version do you have (pip freeze -l)?

**Comment by danpejobo** [comment]
> What version do you have (pip freeze -l)? What version of numpy and pandas? And what OS are you on?

I'm on windows 10. The environment is OSGeo4W. QGIS for windows.
```
C:\OSGeo4W64>python --version
Python 3.9.5

C:\OSGeo4W64>pip -V
pip 21.3.1 from C:\OSGEO4~1\apps\Python39\lib\site-packages\pip (python 3.9)

C:\OSGeo4W64>pip freeze -l
appdirs==1.4.4
beautifulsoup4==4.10.0
bs4==0.0.1
cchardet==2.1.7
certifi==2021.10.8
chardet==3.0.4
colorama==0.4.4
coverage==5.3
cssselect==1.1.0
cycler==0.10.0
decorator==4.4.2
ExifRead==2.3.2
fake-useragent==0.1.11
fonttools==4.28.5
future==0.18.2
GDAL==3.4.1
geographiclib==1.50
httplib2==0.18.1
idna==2.10
importlib-metadata==4.10.0
Jinja2==2.11.2
kiwisolver==1.2.0
libnadagclient==0.0.2
libsgfdata==0.0.10
lxml==4.6.2
MarkupSafe==1.1.1
matplotlib==3.5.1
mock==4.0.2
networkx==2.5
nose2==0.9.2
numpy==1.20.2
OWSLib==0.25.0
packaging==20.4
pandas==1.1.3
parse==1.19.0
Pillow==8.0.1
plotly==4.12.0
ply==3.11
psycopg2-binary==2.8.6
pyee==8.2.2
Pygments==2.7.2
pyodbc==4.0.30
PyOpenGL==3.1.5
pyparsing==2.4.7
pypiwin32==223
pyppeteer==1.0.2
pyproj==3.2.1
PyQt5==5.15.4
PyQt5-sip==12.8.1
pyquery==1.4.3
python-dateutil==2.8.1
python-slugify==5.0.2
pytz==2020.1
pywin32==228
PyYAML==5.3.1
requests==2.24.0
requests-html==0.10.0
retrying==1.3.3
scipy==1.6.2
Shapely==1.7.1
simplejson==3.17.2
sip @ file:///D:/src/osgeo4w/src/python3-sip/sip-6.1.1/dist/sip-6.1.1-cp39-cp39-win_amd64.whl
six==1.15.0
soupsieve==2.3.1
text-unidecode==1.3
toml==0.10.1
tqdm==4.62.3
urllib3==1.25.11
w3lib==1.22.0
websockets==10.1
wxPython @ file:///D:/src/osgeo4w/src/python3-wxpython/wxPython-4.1.1/dist/wxPython-4.1.1-cp39-cp39-win_amd64.whl
xlrd==1.2.0
xlwt==1.3.0
zipp==3.7.0
```

**Comment by redhog** [comment]
I just tested on a clean Ubuntu 20.04.3 LTS:

```
apt install python3.9 python3-pip python3-virtualenv
virtualenv --python=python3.9 env
source env/bin/activate
pip install libsgfdata
python -c "import libsgfdata"
```

works fine.

The versions this installs are (please compare with your versions):

```
cchardet==2.1.7
libsgfdata==0.0.10
numpy==1.22.0
pandas==1.3.5
python-dateutil==2.8.2
python-slugify==5.0.2
pytz==2021.3
six==1.16.0
text-unidecode==1.3
```

**Comment by redhog** [comment]
Thanks. Will try with the same versions.

**Comment by redhog** [comment]
Ok, I can reproduce the bug using your versions. Will fix.

**Comment by danpejobo** [comment]
> Ok, I can reproduce the bug using your versions. Will fix.

Thanks. I will try upgrading the packages in my install

**Comment by redhog** [comment]
It wasn't a complicated thing to solve actually, and all depended on certain pandas versions not liking certain ways of mistreating NaN:s. I have fixed the issue and pushed a new version to pypi, version 0.0.12, so just `pip install --upgrade libsgfdata` and let me know if everything works after that!

**Comment by danpejobo** [comment]
> It wasn't a complicated thing to solve actually, and all depended on certain pandas versions not liking certain ways of mistreating NaN:s. I have fixed the issue and pushed a new version to pypi, version 0.0.12, so just `pip install --upgrade libsgfdata` and let me know if everything works after that!

Seems to be working fine now! Thanks alot!

**Comment by redhog** [comment]
NP :)
